---
name: automerge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'
jobs:
  automerge-on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' }}
    uses: networkservicemesh/.github/.github/workflows/automerge.yaml@main

  automerge-otherwise:
      name: Automerge
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion != 'success' && github.actor == 'nsmbot' }}
      steps:
        - name: Set status 'failure'
          run: |
            echo Set status 'failure' for 'automerge' workflow to prevent run "update dependent repositories" or any other dependent workflows'
            exit -1
